const STATUS_CODE = {
    0: "Giao dịch thành công.",
    9000: "Giao dịch đã được xác nhận thành công.",
    8000: "Giao dịch đang ở trạng thái cần được người dùng xác nhận thanh toán lại.",
    7000: "Giao dịch đang được xử lý.",
    1000: "Giao dịch đã được khởi tạo, chờ người dùng xác nhận thanh toán.",
    11: "Truy cập bị từ chối.",
    12: "Phiên bản API không được hỗ trợ cho yêu cầu này.",
    13: "Xác thực doanh nghiệp thất bại.",
    20: "Yêu cầu sai định dạng.",
    21: "Số tiền giao dịch không hợp lệ.",
    40: "RequestId bị trùng.",
    41: "OrderId bị trùng.",
    42: "OrderId không hợp lệ hoặc không được tìm thấy.",
    43: "Yêu cầu bị từ chối vì xung đột trong quá trình xử lý giao dịch.",
    1001: "Giao dịch thanh toán thất bại do tài khoản người dùng không đủ tiền.",
    1002: "Giao dịch bị từ chối do nhà phát hành tài khoản thanh toán.",
    1003: "Giao dịch bị đã bị hủy.",
    1004: "Giao dịch thất bại do số tiền thanh toán vượt quá hạn mức thanh toán của người dùng.",
    1005: "Giao dịch thất bại do url hoặc QR code đã hết hạn.",
    1006: "Giao dịch thất bại do người dùng đã từ chối xác nhận thanh toán.",
    1007: "Giao dịch bị từ chối vì tài khoản người dùng đang ở trạng thái tạm khóa.",
    1026: "Giao dịch bị hạn chế theo thể lệ chương trình khuyến mãi.",
    1080: "Giao dịch hoàn tiền bị từ chối. Giao dịch thanh toán ban đầu không được tìm thấy.",
    1081: "Giao dịch hoàn tiền bị từ chối. Giao dịch thanh toán ban đầu có thể đã được hoàn.",
    2001: "Giao dịch thất bại do sai thông tin liên kết.",
    2007: "Giao dịch thất bại do liên kết hiện đang bị tạm khóa.",
    3001: "Liên kết thất bại do người dùng từ chối xác nhận.",
    3002: "Liên kết bị từ chối do không thỏa quy tắc liên kết.",
    3003: "Hủy liên kết bị từ chối do đã vượt quá số lần hủy.",
    3004: "Liên kết này không thể hủy do có giao dịch đang chờ xử lý.",
    4001: "Giao dịch bị hạn chế do người dùng chưa hoàn tất xác thực tài khoản.",
    4010: "Quá trình xác minh OTP thất bại.",
    4011: "OTP chưa được gửi hoặc hết hạn.",
    4100: "Giao dịch thất bại do người dùng không đăng nhập thành công.",
    4015: "Quá trình xác minh 3DS thất bại.",
    10: "Hệ thống đang được bảo trì.",
    99: "Lỗi không xác định."
};
exports.getMessage = (code) => {
    return STATUS_CODE[code] || "Lỗi không xác định.";
};